# Generated by Django 4.2 on 2023-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='new_weight',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='recent_weight',
            field=models.FloatField(default=models.FloatField(max_length=6), max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='starting_weight',
            field=models.FloatField(max_length=6),
        ),
    ]
