# Generated by Django 4.2 on 2023-05-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_public_id_alter_patient_recent_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
