# Generated by Django 4.2 on 2023-05-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patient_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='public_id',
        ),
    ]
