# Generated by Django 4.2.1 on 2023-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='BMI',
            field=models.FloatField(max_length=3, null=True),
        ),
    ]
